# Keep all in alphabetical order
components:
  hooks/open-telemetry:
    - beeme1mr
    - Kavindu-Dodan
    - thiyagu06
    - toddbaert
  providers/env-var:
    - madhead
    - toddbaert
  providers/flagd:
    - beeme1mr
    - Kavindu-Dodan
    - toddbaert
    - thisthat
  providers/flagsmith:
    - ajhelsby
    - matthewelwell
  providers/go-feature-flag:
    - thomaspoignant
  providers/jsonlogic-eval-provider:
    - justinabrahms
  providers/unleash:
    - liran2000
    - sighphyre
  providers/flipt:
    - liran2000
    - markphelps
  providers/configcat:
    - liran2000
    - z4kn4fein
    - laliconfigcat
    - novalisdenahi

ignored-authors:
  - renovate-bot
