package dev.openfeature.contrib.tools.tck;

import dev.openfeature.sdk.OpenFeatureAPI;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * What this TCK build is, and which conformance artifacts it carries.
 *
 * <p>A conformance report has to say which questions were asked, not only what the answers were, and
 * neither fact is available from the running code. The spec revision the packaged Gherkin came from
 * is a property of the build — the artifacts are in the JAR, the repository they came from is not —
 * so it is baked into a generated resource at build time and read back here. The SDK version is the
 * opposite case: the TCK depends on a version <em>range</em>, so what a consumer actually ran
 * against is only knowable at runtime.
 *
 * <p>Everything here degrades to {@code unknown} rather than throwing. A report that is slightly
 * less identifiable is worth more than a test run that fails while tidying up after itself.
 */
final class TckBuildInfo {

    /** Which TCK implementation this is, in the form the report schema asks for. */
    static final String IMPLEMENTATION = "java-sdk-contrib/tools/tck";

    /** Maven coordinates of the SDK, reported without a version. */
    static final String SDK_NAME = "dev.openfeature:sdk";

    /** Stands in for anything the build or the classpath could not tell us. */
    static final String UNKNOWN = "unknown";

    private static final Logger log = LoggerFactory.getLogger(TckBuildInfo.class);

    /** Generated by the build from the module POM; see {@code src/main/resources-filtered}. */
    private static final String BUILD_PROPERTIES = "tck-build.properties";

    /** Written into every JAR by maven-archiver, and the most direct statement of what resolved. */
    private static final String SDK_POM_PROPERTIES = "META-INF/maven/dev.openfeature/sdk/pom.properties";

    private static final Properties BUILD = loadBuildProperties();

    private TckBuildInfo() {}

    /** Returns the version of this TCK module. */
    static String tckVersion() {
        return property("tck.version");
    }

    /** Returns the open-feature/spec commit the packaged conformance artifacts came from. */
    static String specRevision() {
        return property("spec.revision");
    }

    /**
     * Returns the OpenFeature SDK version that was actually on the classpath.
     *
     * <p>Read rather than declared. The TCK depends on an SDK version range so that adopting it can
     * never force an upgrade, which means the version is a property of the consumer's build; a
     * hardcoded one would be a second place to be wrong.
     */
    static String sdkVersion() {
        Properties pom = load(SDK_POM_PROPERTIES);
        if (pom != null) {
            String version = pom.getProperty("version", "").trim();
            if (!version.isEmpty()) {
                return version;
            }
        }

        // The Maven descriptor can be stripped, or the SDK can arrive from somewhere that is not a
        // JAR at all — an IDE's output directory, say — so fall back to the manifest.
        Package sdkPackage = OpenFeatureAPI.class.getPackage();
        String implementation = sdkPackage == null ? null : sdkPackage.getImplementationVersion();
        if (implementation != null && !implementation.trim().isEmpty()) {
            return implementation.trim();
        }

        log.warn(
                "Could not determine the OpenFeature SDK version from {} or from the package manifest; "
                        + "the conformance report will say '{}'",
                SDK_POM_PROPERTIES,
                UNKNOWN);
        return UNKNOWN;
    }

    private static String property(String key) {
        String value = BUILD.getProperty(key, "").trim();
        return value.isEmpty() ? UNKNOWN : value;
    }

    private static Properties loadBuildProperties() {
        Properties properties = load(packagePath() + BUILD_PROPERTIES);
        if (properties == null) {
            log.warn(
                    "{} is missing from the TCK JAR, so a conformance report cannot identify the build "
                            + "that produced it. This means the resource filtering configured in the "
                            + "tck POM did not run.",
                    BUILD_PROPERTIES);
            return new Properties();
        }
        return properties;
    }

    private static String packagePath() {
        return TckBuildInfo.class.getPackage().getName().replace('.', '/') + "/";
    }

    private static Properties load(String resource) {
        ClassLoader loader = TckBuildInfo.class.getClassLoader();
        try (InputStream in = loader.getResourceAsStream(resource)) {
            if (in == null) {
                return null;
            }
            Properties properties = new Properties();
            properties.load(in);
            return properties;
        } catch (IOException e) {
            log.warn("Could not read {} from the classpath", resource, e);
            return null;
        }
    }
}
